type ClassEntry = readonly [name: string, tags: readonly string[]];

/** The decoded reflection database Rojo bundles: a tuple whose second element maps each class name to `[name, tags, ...]`. */
export type ReflectionDatabase = readonly [
	unknown,
	Readonly<Record<string, ClassEntry>>,
	...unknown[],
];

// Tagged Service like any other, but reserved for Roblox's own scripts.
const RESERVED_SERVICES: readonly string[] = ["CoreGui", "CorePackages"];

/** Throws when a reserved service is missing, so a renamed one is noticed rather than let through. */
export function selectServices(database: ReflectionDatabase): string[] {
	const services = Object.values(database[1])
		.filter(([, tags]) => tags.includes("Service"))
		.map(([name]) => name);
	const missing = RESERVED_SERVICES.filter(
		(name) => !services.includes(name)
	);
	if (missing.length > 0) {
		throw new Error(
			`Reserved services not in the database: ${missing.join(", ")}`
		);
	}
	return services.filter((name) => !RESERVED_SERVICES.includes(name)).sort();
}

export function renderServicesModule(
	names: readonly string[],
	rojoVersion: string
): string {
	const entries = names.map((name) => `\t"${name}",\n`).join("");
	return `// Generated by scripts/generate-services.ts. Do not edit.
export const SERVICES_ROJO_VERSION = "${rojoVersion}";

export const SUPPORTED_SERVICES = [
${entries}] as const;

export type SupportedService = (typeof SUPPORTED_SERVICES)[number];

const SERVICE_NAMES: ReadonlySet<string> = new Set(SUPPORTED_SERVICES);

export function isSupportedService(name: string): name is SupportedService {
	return SERVICE_NAMES.has(name);
}
`;
}
