type ClassEntry = readonly [name: string, tags: readonly string[]];

/** The decoded reflection database Rojo bundles: a tuple whose second element maps each class name to `[name, tags, ...]`. */
export type ReflectionDatabase = readonly [
	unknown,
	Readonly<Record<string, ClassEntry>>,
	...unknown[],
];

const ROBLOX_INTERNAL_SERVICE = /^Core/;

export function selectServices(database: ReflectionDatabase): string[] {
	return Object.values(database[1])
		.filter(([, tags]) => tags.includes("Service"))
		.map(([name]) => name)
		.filter((name) => !ROBLOX_INTERNAL_SERVICE.test(name))
		.sort();
}

export function renderServicesModule(names: readonly string[]): string {
	const entries = names.map((name) => `\t"${name}",\n`).join("");
	return `// Generated by scripts/generate-services.ts. Do not edit.
export const SUPPORTED_SERVICES = [
${entries}] as const;

export type SupportedService = (typeof SUPPORTED_SERVICES)[number];

const SERVICE_NAMES: ReadonlySet<string> = new Set(SUPPORTED_SERVICES);

export function isSupportedService(name: string): name is SupportedService {
	return SERVICE_NAMES.has(name);
}
`;
}
