export interface ApiDump {
	readonly Classes: readonly {
		readonly Name: string;
		readonly Tags?: readonly string[];
	}[];
}

const ROBLOX_INTERNAL_SERVICE = /^Core/;

/** `isKnownToRojo` is only asked about candidates that survive every other rule, since answering it means running Rojo. */
export function selectServices(
	dump: ApiDump,
	isKnownToRojo: (name: string) => boolean
): string[] {
	return dump.Classes.filter((c) => c.Tags?.includes("Service"))
		.map((c) => c.Name)
		.filter((name) => !ROBLOX_INTERNAL_SERVICE.test(name))
		.filter(isKnownToRojo)
		.sort();
}

export function renderServicesModule(names: readonly string[]): string {
	const entries = names.map((name) => `\t"${name}",\n`).join("");
	return `// Generated by scripts/generate-services.ts. Do not edit.
export const SUPPORTED_SERVICES = [
${entries}] as const;

export type SupportedService = (typeof SUPPORTED_SERVICES)[number];

const SERVICE_NAMES: ReadonlySet<string> = new Set(SUPPORTED_SERVICES);

export function isSupportedService(name: string): name is SupportedService {
	return SERVICE_NAMES.has(name);
}
`;
}
