import fs from "fs";
import path from "path";
import { pathToFileURL } from "url";

export const PAGE = path.resolve("docs/content/docs/v2/agents.mdx");
export const OUTPUT = path.resolve("src/domain/init/agent-hook.ts");

/** The Stop hook script of the agents page, as the module that embeds it holds it. */
export function renderAgentHookModule(page: string): string {
	const script =
		/```bash title="\.agents\/hooks\/rogen-check\.sh"\n([\s\S]*?)\n```/.exec(
			page.replace(/\r\n/g, "\n")
		)?.[1];
	if (!script)
		throw new Error("The agents page has no rogen-check.sh script.");
	return `// Generated by scripts/generate-agent-hook.ts. Do not edit.
/** The agent Stop hook that reports Rogen warnings about the files a turn changed. */
export const agentHook = ${JSON.stringify(`${script}\n`)};
`;
}

export function currentAgentHookModule(): string {
	return renderAgentHookModule(fs.readFileSync(PAGE, "utf8"));
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
	fs.writeFileSync(OUTPUT, currentAgentHookModule());
	console.log(`Wrote ${path.relative(process.cwd(), OUTPUT)}`);
}
