import fs from "fs";
import path from "path";
import { pathToFileURL } from "url";

export const SKILL = path.resolve("skills/rogen/SKILL.md");
export const OUTPUT = path.resolve("src/domain/init/agent-block.ts");

/** The skill's block with its markers, as the module that embeds it holds it. */
export function renderAgentBlockModule(skill: string): string {
	const block = /<!-- rogen -->\n[\s\S]*?\n<!-- \/rogen -->/.exec(
		skill.replace(/\r\n/g, "\n")
	)?.[0];
	if (!block) throw new Error("The skill has no <!-- rogen --> block.");
	return `// Generated by scripts/generate-agent-block.ts. Do not edit.
/** Rogen's rules for coding agents, between the markers that tell \`init\` the block is already there. */
export const agentBlock = ${JSON.stringify(`${block}\n`)};
`;
}

export function currentAgentBlockModule(): string {
	return renderAgentBlockModule(fs.readFileSync(SKILL, "utf8"));
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
	fs.writeFileSync(OUTPUT, currentAgentBlockModule());
	console.log(`Wrote ${path.relative(process.cwd(), OUTPUT)}`);
}
