import { DOCS_URL } from "../src/platform/product/product-service.js";

const SECTION = /^### `([^`]+)` \[#[a-z-]+\]$/;
const SITE = DOCS_URL.replace(/\/docs\/v2$/, "");

/** A docs page's markdown as plain lines: a link becomes its text and its address, and an example is indented instead of fenced. */
function asPlainText(markdown: string): string {
	const lines: string[] = [];
	let inExample = false;
	for (const line of markdown.split("\n")) {
		if (line.startsWith("```")) {
			inExample = !inExample;
			continue;
		}
		lines.push(
			inExample
				? `  ${line}`
				: line
						.replace(/\[([^\]]+)\]\(#[^)]+\)/g, "$1")
						.replace(/\[([^\]]+)\]\((\/[^)]+)\)/g, `$1 (${SITE}$2)`)
		);
	}
	return lines.join("\n").trim();
}

/** Each code's section of the diagnostics page, headed by the code, as `rogen help <code>` prints it. */
export function diagnosticSections(page: string): Record<string, string> {
	const sections: Record<string, string> = {};
	let code: string | undefined;
	let body: string[] = [];
	const close = () => {
		if (code) sections[code] = `${code}\n\n${asPlainText(body.join("\n"))}`;
	};
	for (const line of page.replace(/\r\n/g, "\n").split("\n")) {
		const heading = SECTION.exec(line);
		if (heading || line.startsWith("#")) {
			close();
			code = heading?.[1];
			body = [];
		} else body.push(line);
	}
	close();
	return sections;
}

/** The module that embeds the help topics and the diagnostics page, so a binary needs no file beside it. */
export function renderHelpModule(
	topics: Readonly<Record<string, string>>,
	diagnosticsPage: string
): string {
	const entries = (record: Readonly<Record<string, string>>) =>
		Object.keys(record)
			.sort()
			.map(
				(key) =>
					`\t\t${JSON.stringify(key)}: ${JSON.stringify(record[key])},\n`
			)
			.join("");
	const topicTexts = Object.fromEntries(
		Object.entries(topics).map(([name, text]) => [
			name,
			text.replace(/\r\n/g, "\n").trim(),
		])
	);
	return `// Generated by scripts/generate-help.ts. Do not edit.
/** The text of each help topic and each diagnostic code's section, by name. */
export const helpTexts: {
	readonly topics: Readonly<Record<string, string>>;
	readonly diagnostics: Readonly<Record<string, string>>;
} = {
	topics: {
${entries(topicTexts)}	},
	diagnostics: {
${entries(diagnosticSections(diagnosticsPage))}	},
};
`;
}
